preload = ~/.config/hypr/wallpapers/rias-gremory.jpg
preload = ~/.config/hypr/wallpapers/ruins.jpg
preload = ~/.config/hypr/wallpapers/cyberpunk.jpg
preload = ~/.config/hypr/wallpapers/valley.jpg

wallpaper = DP-3,~/.config/hypr/wallpapers/rias-gremory.jpg
wallpaper = DP-4,~/.config/hypr/wallpapers/cyberpunk.jpg


